### ISSUE TITLE
J_BottomUp actinic flux units in description

### ISSUE THREAD

**Issue by zmoon** [AirChem/F0AM#12]
It says here that the units should be photons/cm^2/s

https://github.com/AirChem/F0AM/blob/e41eba52b792424b8b63f382d9c37be4f0aef2f9/Chem/Photolysis/J_BottomUp.m#L12-L15

but `IntegrateJ.m` really wants it in spectral actinic flux units, photons/cm^2/s/nm

**Comment by gmwolfe** [comment]
Fixed v4.0.2
