### ISSUE TITLE
Inquiry Regarding the Model Correction Factor jcorr

### ISSUE THREAD

**Issue by Hankeran** [AirChem/F0AM#22]
Dear F0AM Developer,

Greetings!

I am an interested user of your developed model. While studying your model, I encountered some questions and am writing to seek clarification.

I have noticed that there is a correction factor in the model called jcorr. I would like to know the range of values this correction factor can take, specifically whether it can be greater than 1. If so, under what circumstances would its value exceed 1?

Thank you very much for taking the time to read my email amidst your busy schedule, and I look forward to your response.

Best regards

**Comment by gmwolfe** [comment]
Hi Hankeran,

Yes, jcorr can exceed 1.  In the real world, j-values can exceed their clear-sky values if you are in a reflective environment, e.g. above clouds. The J-value parameterizations in F0AM do not have explicit dependence on clouds or aerosol.

In the future, please post questions to the user forum on Google Groups, which is linked in the ReadMe.

Regards,

~Glenn
